### ISSUE TITLE
Link to the pretrained weights file in the ReadMe.md is incorrect

### ISSUE THREAD

**Issue by Greendogo** [torrvision/siamfc-tf#1]
The link to the pretrained weights file in the ReadMe.md, step #8, is incorrect.  It should point to (I believe) an archive containing "baseline-conv5_e55.mat".  However, the link is a duplicate of the link pointing to "cfnet_validation_set.zip" (which is given in step #9, regarding the video sequences).

Since this version is not made to train yet, the project cannot be used at all until this file is provided.

**Comment by bertinetto** [comment]
Oh yeah you are right, solved now. Thanks for pointing it out!
