### ISSUE TITLE
trying to work with webcam

### ISSUE THREAD

**Issue by rnunziata** [torrvision/siamfc-tf#15]
I was trying to get this to work with a webcam...by using pyyolo. but could not get the tracker to work by repeated calls by image. Box would either track to image center or remain fixed and not track object. Any help how to set up tracker so to call it in a loop over images.

**Comment by ginko3** [comment]
First things first, the network takes as input a path to an image rather than an image itself. In your case, it's simpler to change the architecture a little, in order to feed the network the images you capture as you're recording.
Hope it helps.

**Comment by rnunziata** [comment]
Thanks...I did  that and had it taking a cam image in a loop....but somehow I was missing a critical parameter...I tried feeding in the ztemplate_ back into subsequent calls but I cold not figure it out. Anyway I will close this.
