### ISSUE TITLE
About model testing

### ISSUE THREAD

**Issue by mingchuan123** [torrvision/siamfc-tf#18]
Hi there, I have noticed that when trying to run the model on my own images, I need to put both images and ground truth in the data folder, which seems just like ploting ground truth on the image. So how does the model track the target? Does the ground truth put in only for IoU computing? Thanks.

**Comment by TheMikeyR** [comment]
I didn't study the code in details (yet), my plan is to manipulate the code to do multiple tracking on my own custom dataset (I don't know if it's possible yet though). But I believe I can answer your question, it seems that they run `_compile_results` to get information to display in the cli. IOU is calculated by using bboxes and gt, which I assume is the tracked bboxes with the groundtruth bboxes, to calculate the precision of the tracker. 

Didn't find it yet but I assume they initialize the tracker with the first ground truth bounding box and then they let the siamfc do rest of the tracking. 

Feel free to let me know if you need any more assistance, I'm analyzing the code now so I might be able to provide better help.

**Comment by mingchuan123** [comment]
Thanks for your reply mike, BTW do you know how to train the model?

2017-11-02 4:36 GMT-04:00 Mike Røntved <notifications@github.com>:

**Comment by TheMikeyR** [comment]
@mingchuan123 I've decided not to look further into it, since the network is only designed for single object tracking, so I'm not able to help you further.

**Comment by bertinetto** [comment]
@mingchuan123 see #20
