### ISSUE TITLE
train script

### ISSUE THREAD

**Issue by dudupig123** [torrvision/siamfc-tf#2]
I have run your tracker . It shows an amazing result. But In my 
environment，I still lose my target . I have not  installed matlab. Can you provide a train script. Thanks.

**Comment by bertinetto** [comment]
Thanks, I am glad it's working well!
We might release a fully tensorflow (or pytorch) implementation towards the end of the year, but it's not sure yet.
I recommend to reimplement it on your own though, it shouldn't be too difficult as the method is pretty simple.

**Comment by he010103** [comment]
@bertinetto Hello, I am interested in siamfc and recently trying to reproduce the training code in pytorch with many problems. When the code of pytorch training code be released ? Thanks!
