### ISSUE TITLE
Compiler error when pip install matplotlib

### ISSUE THREAD

**Issue by magicfish2007** [torrvision/siamfc-tf#22]
Compiler error when pip install matplotlib 1.3.1:

npy_PyFile_DupClose was not declared in this scope

and I find no npy_PyFile_DupClose in numpy's .h file, but just  npy_PyFile_DupClose2 in it.

I also find that npy_PyFile_DupClose was deprecated in numpy 1.9.0:https://github.com/numpy/numpy/blob/7cfec2403486456b52b525eccf7541e1562d9ab3/doc/release/1.9.0-notes.rst

So, I think numpy's version(1.11.1) is too high for matplotlib 1.3.1?

**Comment by magicfish2007** [comment]
I have resolved it.  I should install they with right order.

**Comment by gerrywalsh** [comment]
I have tried to install dependencies with sudo pip install -r requirements.txt, and get the same error - how did you resolve?
