### ISSUE TITLE
why cannot read the data?

### ISSUE THREAD

**Issue by zhangyujia0223** [torrvision/siamfc-tf#24]
Thank you for releasing this code. But I have some problems. Could you help me?
![image](https://user-images.githubusercontent.com/28782048/35086263-664e2a8a-fc6f-11e7-9f07-c81c4b7ed70b.png)
![image](https://user-images.githubusercontent.com/28782048/35086279-738a55c0-fc6f-11e7-80c2-d58b2246f5b7.png)

**Comment by NazneenKotwal** [comment]
Delete the README.txt file as the python code interprets it as a folder directory.
