### ISSUE TITLE
Adapting the code to support multi-object

### ISSUE THREAD

**Issue by lukaswals** [torrvision/siamfc-tf#28]
Problem solved

Thanks for this amazing work :)

**Comment by TheMikeyR** [comment]
@lukaswals Could you share how you managed to solve the problem?

**Comment by lukaswals** [comment]
@TheMikeyR Yes, I will be sharing the code soon. I will announce it here when it's done :)

**Comment by lukaswals** [comment]
@TheMikeyR Sorry for the delay. You can find the multi-object version here -> https://github.com/lukaswals/siamfc-tf

Hope this is useful to you and anyone interested in it
