### ISSUE TITLE
Normalization doubt

### ISSUE THREAD

**Issue by DiegoOrtego** [torrvision/siamfc-tf#37]
In tracker.py, why do you need to perform the following:

score_ = score_ - np.min(score_)
score_ = score_/np.sum(score_)

**Comment by jvlmdr** [comment]
Hey Diego,

I believe this was to ensure that we could use similar settings for the motion penalty (cosine window), regardless of changes that we made to the network (architecture, loss, etc). This setting is only used during tracking, not at training-time.

**Comment by DiegoOrtego** [comment]
Thanks Jack! I was not using it for training, good to confirm it!
Cheers!
