### ISSUE TITLE
Why does output channals be 32?

### ISSUE THREAD

**Issue by aaon22357** [torrvision/siamfc-tf#38]
I have found the output channel is 32 ,but it is 128 in the paper, why are they not equal? Will this affect the accuracy?

**Comment by bertinetto** [comment]
Hi,
32 is the number of channel used in the SiamFC baseline in our CFNet paper,
which works slightly better than original SiamFC (2016) version.

http://www.robots.ox.ac.uk/~luca/cfnet.html
