### ISSUE TITLE
Visualization slows down performance too much

### ISSUE THREAD

**Issue by Greendogo** [torrvision/siamfc-tf#4]
I think the method you're using to visualize the network output is too slow.  I'm sure you've seen this, but using the vot2016_ball1 video without visualization gets speed of 46.70 FPS and with visualization it gets speed of 6.39 FPS.

**Comment by bertinetto** [comment]
You are right, it's super slow.
It was just a way to check things are working alright.

Thanks for sharing your code and for the pull request. I will try to merge soon

**Comment by mingchuan123** [comment]
Hi @Greendogo , which platform are you running on to get a fps of 46.70? Which GPU? Thanks
