### ISSUE TITLE
What is the value of T (2 frames are choosen at most T frames apart)?

### ISSUE THREAD

**Issue by maklachur** [torrvision/siamfc-tf#46]
In the training time, they mentioned images are extracted from two frames of a video that both contain the object and are at most T frames apart.
Is there any specific way to select T, or these 2 frames?

**Comment by bertinetto** [comment]
Hi,
Consider it as a tradeoff between robustness to important or small
appearance changes.
If you are trying to improve the expected performance on a wide variety of
scenarios, (like all the hyperparameters) you can select it via
cross-validation.
Hope this helps,
Luca

**Comment by maklachur** [comment]
Thank you so much for your information.
