### ISSUE TITLE
The baseline-conv5_e55.mat can't download

### ISSUE THREAD

**Issue by Breakmydream** [torrvision/siamfc-tf#7]
the web can't open

**Comment by bertinetto** [comment]
Hi,
I have tested both link now and they seem to works.

Try [the Google Drive linkl]( https://drive.google.com/open?id=0B7Awq_aAemXQZ3JTc2l6TTZlQVE) or the [FTP link](https://bit.ly/cfnet_networks)

Cheers,

**Comment by Breakmydream** [comment]
Thx 
I had download it in your CFnet web this afternoon

**Comment by li10141110** [comment]
hi,Torr.How can I test rather than evaluate your siamfc-tf model with my own video?

**Comment by li10141110** [comment]
I have frames of my video but I don't know how to get first franme's groundtruth

**Comment by bertinetto** [comment]
Hi,

The tracker is initialized with the bounding box present at the first row
of a groundtruth.txt file provided with the sequences. All the other rows
are used to compute the performance of the method against the ground truth.

You can use your own sequences as well, you just need to specify the first
bounding box. You will have to slightly modify the code, but it should be
straightforward.

On the project page you can download sample sequences in the compatible
format as example.

**Comment by li10141110** [comment]
Thank you very much!
